default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [ '--maxkb=4000' ]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]

  #  - repo: https://github.com/PyCQA/docformatter
  #    rev: v1.7.5
  #    hooks:
  #      - id: docformatter
  #        additional_dependencies: [ tomli ]
  #        args: [ --in-place, --config, ./pyproject.toml ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ --settings-path pyproject.toml ]

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.2
    hooks:
      - id: doc8
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [ --config=setup.cfg ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml ]

# TODO: fix mypy. It outputs different errors than running it manually.
